name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate Release Notes
      uses: openmrs/openmrs-contrib-releasenotesbuilder@main
      with:
        version: ${{ github.ref_name }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "release_notes.md"
        token: ${{ secrets.GITHUB_TOKEN }}